<div class="abtbanner BgGrdOrange ">
    <div class="container maincontainer">
        <h3>Privacy Policy</h3>
        <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="<?php echo base_url(); ?>"><i class="fas fa-home"></i> Home</a></li>
            <li class="breadcrumb-item active" aria-current="page">Privacy Policy</li>
        </ol>
    </div>
</div>
<section class="inner_page_wrapper">
    <div class="container maincontainer">
        <div class="row">
        <div class="col-xl-12 col-lg-12 col-md-12 col-sm-12 col-12">
                
<br>
<span style="font-size:12pt"><span style="font-family:Regular; font-size: 14px;"><span style="color:black"><span lang="EN-US" style="font-size:16.0pt">Direction Group of Institutions Privacy policy</span></span></span></span><br>
<br>
<span style="font-size:12pt"><span style="font-family:Regular; font-size: 14px;"><span style="color:black">This privacy policy sets out how Direction Group of Institutions Pvt Ltd (DGIPL) uses and protects any information that you give DGIPL when you use this website.</span></span></span><br>
<br>
<span style="font-size:12pt"><span style="font-family:Regular; font-size: 14px;"><span style="color:black">DGIPL is committed to ensuring that your privacy is protected. Should we ask you to provide certain information by which you can be identified when using this website, then you can be assured that it will only be used in accordance with this privacy statement.</span></span></span><br>
<br>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">DGIPL may change this policy from time to time by updating this page. You should check this page from time to time to ensure that you are happy with any changes. This policy is effective from 09th Sep 2019.</span></span></span></span></span></span><br>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Direction.org.in collects and uses personal data as needed in order for us to provide you educational services. Your personal data includes information such as:</span></span></span></span></span></span>
</p>
<ul>
	<li style="text-align:justify; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Name</span></span></span></span></span></span></li>
	<li style="text-align:justify; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Address</span></span></span></span></span></span></li>
	<li style="text-align:justify; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Phone number</span></span></span></span></span></span></li>
	<li style="text-align:justify; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Email address</span></span></span></span></span></span></li>
	<li style="text-align:justify; margin-bottom:11px; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Other data that could directly or indirectly identify you.</span></span></span></span></span></span></li>
</ul>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style=""><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span style="letter-spacing:.25pt">Our Privacy Policy will explain to you what data we collect, and how we use your personal data. It also describes how you can access, update, or otherwise take control of the personal data that we have collected from you.</span></span></span></span></span></span></span></span><br>
<br><p>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><b><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span style="color:black">What data is collected?</span></span></span></span></b></span></span></span><br>
</p>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Most of your personal data is collected from you when:</span></span></span></span></span></span>
<br>
<ul>
	<li style="text-align:justify; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">You sign up for our services;</span></span></span></span></span></span></li>
	<li style="text-align:justify; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">You request assistance from our customer support team;</span></span></span></span></span></span></li>
	<li style="text-align:justify; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">You complete surveys, subscribe to newsletters, or request other information from us;</span></span></span></span></span></span></li>
	<li style="text-align:justify; margin-bottom:11px; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">You participate in contests, apply for a job, or participate in activities where we may require information about you.</span></span></span></span></span></span></li>
</ul>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><b><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">In order to deliver the best Services to you, we may collect the following information:</span></span></span></b></span></span></span><br><br>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Account related information&nbsp;is collected when you sign up for our Services. This information may include your name, address, phone number, email address, credit card information, etc.</span></span></span></span></span></span><br>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Service Usage Data&nbsp;is automatically collected when you interact with our Services. This information may include data about your interactions with the features, content and links contained in our Services, time of interaction, browser type and configuration, operating system used, IP address, language preferences, and other cookie data. While none of this data will allow us to directly identify who you are, some of this data can be used to approximate your location. </span></span></span></span></span></span><br>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Supplementary Data&nbsp;may be received about you from third party sources, such as public databases. We may combine this data with the information we already have about you in order to maintain accuracy of our records, and provide products and services that you may be interested in.</span></span></span></span></span></span><br>
<br><p>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><b><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span style="color:black">How we use data</span></span></span></span></b></span></span></span><br>
</p>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">We believe in minimizing the data we collect. We will only use your data when we have been given permission to do so, when it is needed to deliver the Services that you have purchased, or for legal compliance or other lawful purposes. These usages include:</span></span></span></span></span></span><br>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Delivering, updating, and improving the Services that we provide to you.&nbsp;We collect various data relating to your interactions with our Services. We use this data to:</span></span></span></span></span></span>
<br>
<ul>
	<li style="text-align:justify; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Improve and optimize the performance of our Services</span></span></span></span></span></span></li>
	<li style="text-align:justify; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Identify and investigate security risks, errors, problems, and needed enhancements to our Services</span></span></span></span></span></span></li>
	<li style="text-align:justify; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Detect and prevent fraud and abuse of our Services</span></span></span></span></span></span></li>
	<li style="text-align:justify; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Collect statistics about the use of our Services</span></span></span></span></span></span></li>
	<li style="text-align:justify; margin-bottom:11px; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Analyze how you use our Services and which of our Services are most relevant to you</span></span></span></span></span></span></li>
</ul>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Most of the data that we collect is statistical data about how people use our Services and is not linked to any personal data.</span></span></span></span></span></span><br>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Sharing with trusted third parties.&nbsp;We may share your personal data with affiliated companies within our corporate family and with trusted third-party service providers in order for them to perform certain tasks on our behalf. This may include:</span></span></span></span></span></span>
<br>
<ul>
	<li style="text-align:justify; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Processing credit card payments</span></span></span></span></span></span></li>
	<li style="text-align:justify; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Delivering content and communications to you (such as email)</span></span></span></span></span></span></li>
	<li style="text-align:justify; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Analyzing Service usage and customer demographics</span></span></span></span></span></span></li>
	<li style="text-align:justify; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Serving advertisements</span></span></span></span></span></span></li>
	<li style="text-align:justify; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Conducting surveys or contests</span></span></span></span></span></span></li>
	<li style="text-align:justify; margin-bottom:11px; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Managing customer relationships</span></span></span></span></span></span></li>
</ul>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">We only share what is needed for the third party to perform the tasks on our behalf. These third parties are prohibited from using, sharing, or keeping your personal data for any other purpose, and are bound to strict data processing terms and conditions.</span></span></span></span></span></span><br>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Communicating with you.&nbsp;We may contact you directly or through a third-party service provider regarding the Services that you have purchased or subscribed to. We may also contact you with offers for additional services if you give us consent, or when it is allowed based on legitimate interests. The methods of contact may include:</span></span></span></span></span></span>
<br>
<ul>
	<li style="text-align:justify; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Email</span></span></span></span></span></span></li>
	<li style="text-align:justify; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Phone calls</span></span></span></span></span></span></li>
	<li style="text-align:justify; margin-bottom:11px; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Text messages</span></span></span></span></span></span></li>
</ul>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">You may revert back on services feedback or any other info required through the "Contact Us" section.</span></span></span></span></span></span><br>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Website analytics.&nbsp;We use various third-party web analytics tools such as Google Analytics to collect information on how you interact with our website. This data may include information on which pages you visit, how much time you spend on each page, which operating system and browser you use, and geographic location information. These tools will place cookies in your browser for this purpose which can only be used by the service provider. The data collected may be transmitted to and stored by these service providers in a country other than where you reside. This information does not include personal data such as names, address, email addresses, etc, and will be stored and used in accordance with their own privacy policies.&nbsp; </span></span></span></span></span></span><br>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Compliance with legal, regulatory, and law enforcement requests.&nbsp;We cooperate with law enforcement and government officials and private parties to comply with the law. We will, in our sole discretion, disclose any information about you to such parties as necessary to respond to claims and legal processes, to protect our property and rights or the property and rights of a third party, to protect the safety of the public or an individual, or to prevent or stop illegal or unethical activity.</span></span></span></span></span></span><br>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">If we are legally permitted to do so, we will take reasonable steps to notify you in the event we are required to provide your information to third parties as part of a legal process.</span></span></span></span></span></span><br>
<br><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><b><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span style="color:black">How we secure and retain data</span></span></span></span></b></span></span></span><br><br>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">We follow generally accepted standards to collect, store and protect personal data, including the use of encryption. We retain personal data for as long as it is needed to provide the Services you have requested, and thereafter for legal and business purposes. These may include retention periods:</span></span></span></span></span></span>

<ul>
	<li style="text-align:justify; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Mandated by legal, contractual, or similar obligations;</span></span></span></span></span></span></li>
	<li style="text-align:justify; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">For resolving, preserving, enforcing or defending our legal and contractual rights;</span></span></span></span></span></span></li>
	<li style="text-align:justify; margin-bottom:11px; margin-left:8px"><span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Needed to maintain adequate and accurate business and financial records.</span></span></span></span></span></span></li>
</ul>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><b><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span style="color:black">How you can access, update, or delete your data</span></span></span></span></b></span></span></span><br><br>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">You can access, view and update your personal data by signing into your account and visiting "My Account". If you are unable to access "My Account" for any reason, you may contact us as described in the "Contact Us" section below.</span></span></span></span></span></span><br>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">If you make a request to delete your personal data, that request will be honored only to the extent where the data is no longer needed for the Services you have purchased, or when it is no longer required for our business, legal or contractual record keeping requirements.</span></span></span></span></span></span><br>
<br>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><b><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span style="color:black">Age restrictions</span></span></span></span></b></span></span></span><br><br>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Our Services are only available for purchase for those who are over the age of 18. Our Services are not designed to target, entice, or consumed by individuals under the age of 18. If you know of or have reason to believe someone under the age of 18 has provided us with any personal data, please contact us.</span></span></span></span></span></span><br>
<br><p>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><b><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span style="color:black">Changes to our Privacy Policy</span></span></span></span></b></span></span></span><br>
</p>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">We reserve the right to modify this Privacy Policy at any time. Please review this document from time to time so that you are aware of what information we collect and how we use it.</span></span></span></span></span></span><br>
<br><p>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><b><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span style="color:black">Data Protection Authority</span></span></span></span></b></span></span></span><br>
</p>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">we maintain your personal data subject to the General Data Protection Regulation laid down by central/state governments through IT(Information Technology) policies and procedures , you may direct questions or complaints to your local Data Protection Authority.</span></span></span></span></span></span><br>
<br><p>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><b><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span style="color:black">Contact us</span></span></span></span></b></span></span></span><br>
</p>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">If you have any questions or concerns regarding our Privacy Policy, you may contact us by:</span></span></span></span></span></span><br>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><b>Email:</b> enquiry@gmail.com</span></span></span></span></span></span><br>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><b>Mail:</b>&nbsp;</span></span></span></span></span></span><br>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Direction Group of Institutions Pvt Ltd,</span></span></span></span></span></span><br>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Four square Building , 2<sup>nd</sup> and 3<sup>rd</sup> Floors,</span></span></span></span></span></span><br>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;">Tondayad NH-66, Calicut -673017.</span></span></span></span></span></span><br>
<span style="font-size:11pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><span lang="EN-US" style="font-size:12.0pt"><span style="line-height:107%"><span style="font-family:Regular; font-size: 14px;"><b>Phone:</b> 7902777456</span></span></span></span></span></span><br>
<br>
</div>
            <div class="col-xl-4 col-lg-4 col-md-6 col-sm-12 col-12">
                <div class="row">
                    <div class="col-xl-12 col-lg-12 col-md-6 col-sm-12 col-12">
                        <div class="abtboxlist">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>

